### ISSUE TITLE
visit.sequence parameter might need some attention in synthpopDSS

### ISSUE THREAD

**Issue by tombisho** [sib-swiss/dsSwissKnife#1]
Hi, I am working on a synthetic data package for DataSHIELD. It aims to provide some additional features in addition to those that you provide in this package. Plus our users might not want to install all the other functions in `dsSwissKnife`, just the synthetic data functions only. The functions in your package have been a useful inspiration for some of the disclosure traps and I will of course attribute this to you.

I wanted to let you know that I think some more work is needed with the `visit.sequence` parameter. In my tests, if you use this parameter to specify an incomplete set of columns, the columns that are missed out have the real data returned. So I think we either need to block this parameter or force all columns to be referenced.

What do you think?

**Comment by tombisho** [comment]
I should add my initial thought is to allow `visit.sequence` but enforce that it is the same length as the number of columns to be synthesised.

**Comment by IulianD** [comment]
Hi, thanks for the feedback, I'll have a closer look and get back to you.

**Comment by tombisho** [comment]
Looking again, actually I think that by enforcing the value of `drop.not.used` and `drop.pred.only` to be `TRUE` you stop any data leaking!

**Comment by IulianD** [comment]
Hello, I'm not sure I understand, are you saying all is fine? because this is how it looks from my side, I'm already setting those arguments to TRUE, right? Also I performed a small test this morning and it seems to work. If this is not the case I'm missing something, please send me a small test case (you can use test-dssSynthpop.R in dsSwissKnifeClient as a starting point). Cheers.

**Comment by tombisho** [comment]
Hi Iulian, apologies for not being clear and causing confusion. I am now saying everything is working correctly, and everything is OK. I had misunderstood what was happening.
